[workspace]
resolver = "2"

members = [
    "solutions_1-50/problem-44/pentagon-numbers",
    "solutions_1-50/problem-43/sub-string-divisibility",
    "solutions_1-50/problem-42/coded-triangle-numbers",
    "solutions_1-50/problem-41/pandigital-primes",
    "solutions_1-50/problem-40/champernownes-constant",
    "solutions_1-50/problem-39/integer-right-triangles",
    "solutions_1-50/problem-38/pandigital-multiples",
    "solutions_1-50/problem-37/truncatable-primes",
    "solutions_1-50/problem-36/double-base-palindromes",
    "solutions_1-50/problem-35/circular-primes",
    "solutions_1-50/problem-34/digit-factorials",
    "solutions_1-50/problem-33/digit-canceling-fractions",
    "solutions_1-50/problem-32/pandigital-products",
    "solutions_1-50/problem-31/coin-sums",
    "solutions_1-50/problem-30/digit-fifth-powers",
    "solutions_1-50/problem-29/distinct-powers",
    "solutions_1-50/problem-28/number-spiral-diagonals",
    "solutions_651-700/problem-666/polymorphic-bacteria",
    "solutions_*/*/*",
]